name: cloudservicestore_contact_empty

services:
  sqlserver:
    container_name: cloud-service-store-contact-empty-sqlserver
    volumes:
      - contact-empty-sqlserver-data:/var/opt/mssql
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -d master -Q "SELECT 1" || exit 1

  api:
    container_name: cloud-service-store-contact-empty-api
    environment:
      ConnectionStrings__CloudServiceStore: Server=sqlserver,1433;Database=CloudServiceStoreContactEmpty;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True

  migrator:
    environment:
      ConnectionStrings__CloudServiceStore: Server=sqlserver,1433;Database=CloudServiceStoreContactEmpty;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True

volumes:
  contact-empty-sqlserver-data:
